version: '3.8'
services:
    postgresql-db:
        image: postgres:15.3-alpine3.18
        container_name: 'postgresql-simple-pdv'
        volumes:
            - ./database_data:/var/lib/postgresql/data
            - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
        environment:
            POSTGRES_DB: simple-pdv
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: admin123456
        ports:
            - 5432:5432
        networks:
            - backend_services
    app:
        container_name: simple-pdv-api
        build:
            context: .
        networks:
            - backend_services
        ports:
            - 8080:8080
networks:
    backend_services:
        driver: bridge
