spring:
  application:
    name: simple-pdv-api
  datasource:
    #url:  jdbc:h2:mem:simple-pdv
    #username: admin
    #password: 123456
    username: postgres
    password: admin123456
    url: jdbc:postgresql://localhost:5432/simple-pdv
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true